# Form implementation generated from reading ui file '12-Grouping_QRadioButton_with_Designer.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 411)
        Dialog.setStyleSheet("QLabel {\n"
"color:purple\n"
"}")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 191, 41))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 180, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_result = QtWidgets.QLabel(Dialog)
        self.label_result.setGeometry(QtCore.QRect(30, 350, 601, 41))
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        font.setBold(True)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 60, 103, 80))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_py = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        font.setBold(False)
        self.radioButton_py.setFont(font)
        self.radioButton_py.setObjectName("radioButton_py")
        self.radioButton_py.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.radioButton_py)
        self.radioButton_java = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.radioButton_java.setFont(font)
        self.radioButton_java.setObjectName("radioButton_java")
        self.radioButton_java.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.radioButton_java)
        self.radioButton_js = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        font.setBold(False)
        self.radioButton_js.setFont(font)
        self.radioButton_js.setObjectName("radioButton_js")
        self.radioButton_js.toggled.connect(self.radio_selected)
        self.verticalLayout.addWidget(self.radioButton_js)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(30, 230, 149, 80))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_deb = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(12)
        self.radioButton_deb.setFont(font)
        self.radioButton_deb.setObjectName("radioButton_deb")
        self.radioButton_deb.toggled.connect(self.radio_selected)
        self.verticalLayout_2.addWidget(self.radioButton_deb)
        self.radioButton_paypal = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_paypal.setFont(font)
        self.radioButton_paypal.setObjectName("radioButton_paypal")
        self.radioButton_paypal.toggled.connect(self.radio_selected)
        self.verticalLayout_2.addWidget(self.radioButton_paypal)
        self.radioButton_cash = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_cash.setFont(font)
        self.radioButton_cash.setObjectName("radioButton_cash")
        self.radioButton_cash.toggled.connect(self.radio_selected)
        self.verticalLayout_2.addWidget(self.radioButton_cash)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def radio_selected(self):
        selected_one = ""
        selected_two = ""

        if self.radioButton_py.isChecked():
            selected_one = "Python"
        elif self.radioButton_java.isChecked():
            selected_one = "Java"
        elif self.radioButton_js.isChecked():
            selected_one = "JavaScript"

        if self.radioButton_deb.isChecked():
            selected_two = "Debit/Credit Card"
        elif self.radioButton_paypal.isChecked():
            selected_two = "PayPal"
        elif self.radioButton_cash.isChecked():
            selected_two = "Cash"

        self.label_result.setText(f"Chosen Book: {selected_one} - Chosen Payment Method: {selected_two}")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Choose Your Book "))
        self.label_2.setText(_translate("Dialog", "Choose Your Payment Method "))
        self.radioButton_py.setText(_translate("Dialog", "Python"))
        self.radioButton_java.setText(_translate("Dialog", "Java"))
        self.radioButton_js.setText(_translate("Dialog", "JavaScript"))
        self.radioButton_deb.setText(_translate("Dialog", "Debit/Credit Card"))
        self.radioButton_paypal.setText(_translate("Dialog", "Paypal"))
        self.radioButton_cash.setText(_translate("Dialog", "Cash"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
